server:
  port: 9090
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  mail:
    host: smtp.qq.com
    username: 1876218322@qq.com
    password: veyvarduykpqejih
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
  main:
    allow-circular-references: true
  datasource:
    username: root
    password: pinger1234567
    url: jdbc:mysql://47.113.219.144:3306/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    host: 47.113.219.144
    port: 6379
    password: pinger1234567
    timeout: 3200
    jedis: # 设置Redis连接池
      pool:
        max-wait: 2000
        min-idle: 3
        max-idle: 10
        max-active: 10





user:
  code:
    format: 【poetize.cn】%s为本次验证的验证码，请在5分钟内完成验证。为保证账号安全，请勿泄漏此验证码。
